### PR TITLE
use InternalClient IP address

### PR DESCRIPTION
**Pull request by littleskunk**
https://github.com/indutny/node-nat-upnp/issues/22

### CODE REVIEW

**Comment by tomaspinho** [comment]
Any plans to merge this anytime soon? I had to pin version 0.2.1 because 1.0 was not working.

**Comment by indutny** [comment]
@tomaspinho sure!

@littleskunk thank you for the patch! May I ask you to add a bit more description. Right now it is not completely clear, what happens, and how is it fixed.

**Comment by littleskunk** [comment]
It is not realy my fix. swordfeng fixed it some month ago but did not open a pull request.

I would like to call portMapping like this:
```
natupnp.portMapping({
  public: port,
  private: port,
  ttl: 0
}
```

The module detects my upnp device and my ip address (addr) but it fowards my gateway ip (remote.address). My router can't fowards the port to his own ip and refuse the upnp request. By using my ip address (addr) the upnp request is working fine.

**Comment by indutny** [comment]
Landed and released, hope it works! 👍

**Pull request closed without merging**
